#! /bin/bash

cd `dirname $0`

g++ -g -Wall src/*.cpp \
-o build/FlightGame \
\
-lsfml-system \
-lsfml-window \
\
-framework GLUT \
-framework OpenGL \
\
&& echo "----------" \
&& gdb ./build/FlightGame
